### ISSUE TITLE
Add bitrate to video guidelines

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/gdquest-projects#15]
Bitrate is not one of the most obvious things. A standard Full HD 1920x1080 can have a good range of bitrates, I record with 1080 for Pigdev, but researching on the web it can go up to 8192, which is [YoutTube recommended bitrate](https://support.google.com/youtube/answer/1722171?hl=en). I think it would be a good idea to have our standard on the guidelines as well.

**Comment by NathanLovato** [comment]
I'm pretty sure you never use or check the bitrate when you render/encode videos. The video encoder handles that way better than us. And if your video has a high bitrate, youtube will just compress it for you.

There's plenty of work to do on what matters most to me: teaching well. Besides resolution and framerate, which can cause issues when you edit with Blender, or audio processing, essential to get good sound, I want the guidelines to focus on writing, recording, and editing good videos. Not technical details.
