### ISSUE TITLE
GDscript guidelines for clean code: Code Structure

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/gdquest-projects#3]
Tutorial showcasing and explaining our [GDscript guidelines](https://github.com/GDquest/kickstarter-quest-3/blob/master/docs/code-guidelines.md). 

As there's a lot to cover with the guidelines, I think they should be split in 2-3 videos. That's why this task is only about the first section, [code writing style](https://github.com/GDquest/kickstarter-quest-3/blob/master/docs/code-guidelines.md#code-writing-style). The Event bus pattern and system design interactions would deserve their own respective videos.

Should move the guidelines to this repo as well, and have all our guideline docs grouped here?

**Comment by henriiquecampos** [comment]
>Should move the guidelines to this repo as well, and have all our guideline docs grouped here?

Yes!

**Comment by henriiquecampos** [comment]
I think that even this issue could be a 2 parts video as well.

Part I:
Code Structure (the order of the elements, naming conventions, etc..)
Part II:
Good Practices (avoid null, use static typing, write self documenting code)

**Comment by henriiquecampos** [comment]
Alright, video is up. Closing it, can reopen if needed.
