### ISSUE TITLE
The 4 Free Software We Make Games With: Collab with Pigdev

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/gdquest-projects#6]
## My notes/outline

How about we cover the tools we use respectively? For me it'd be krita, godot, blender, tiled, ardour + zynsubfx + calf plugins, emacs/spacemacs
Then darktable, digikam, and nomacs for picture/video management, image library, and raw development

### Krita: Raster 2d art / Show openRPG, YT thumbnails

Krita has had severe stability and performance issues
Each major release brought massive improvements over the past few years
The upcoming 4.2 focuses on bug fixes and polishing the workflow. Selection improvements, color masks, painting, performances...

Krita offers many features. It's an old FOSS project and one worth following
Best parts: Painting feels great, only FOSS drawing and image editing program with nondestructive layers
Builtin stabilizer, mirror drawing and multibrush. Ability to transform a selection and sculpt many layers at the same time, with any transform mode
Excellent options for color selection and color management

We have our own addon, it's fairly easy to create one and extend Krita
Biggest limitations right now for me, for 2d game art and (March 2019): text, which is being worked on, and for me, snapping

### Blender 2.8 / Show mannequiny, tutorials, and Japan vid project

We use Blender for video editing. Blender is customizable. We created our own
add-on that makes editing faster than in most programs Blender is playing in the
big league and is a reference in the world of Free Software, 25 years after it
was open sourced. The upcoming 2.8 release is massive. Tons of new features, beautiful interface.

### Emacs, with the Spacemacs distribution

Programming, writing, web development, project management
Emacs is a hard tool to pick up, but the editor of a lifetime: it helped me understand code and how computer programs work better
Using vim keybindings: wanted to learn and try modal editing/different ux, never looked back. It changed the way I use the computer
It's a tool you configure to the bone, like vim. Thankfully spacemacs brings great defaults and excellent config options + docs. You can get to work quickly with its layers and tweak it as you go.
Complete note taking, project management and agenda system that syncs to my phone
The best git emulation I've worked with (magit)
One tool to write, proof text, code, manage appointments. Can also work as an email client and web browser, or e.g. play music on Spotify

### Godot, the engine you've waited for

Take pitch from Godot slides, show shots from the 3.1 release trailer and ongoing projects
Godot's biggest strengths: dedicated 2d engine, write tools and plugins with regular game code
500+ contributors on the last release, active devs count growing every year
Check our tuts!

**Comment by henriiquecampos** [comment]
Alright! On my end I outlined the following:

## Overall Structure
Each tool will have 4 "sections"

1. What is it
1. How I met it
1. Why I use it
1. Quick work showcase

## Outline
### Intro
Talk about what is Free Open Source Software, hooking for a "Why I use FOSS". How you can start, and probably stick, with FOSS to build a portfolio for a game development career.

### Inkscape: Vector Art, graphic design, graphic assets, scene composition
Inkscape is a Vector Drawing software with a long history. It released its version 0.92 not so much ago, so officially it is not stable yet.

I use Inkscape for most raw graphic design, to draw the shapes, base color, and arrange of objects. I use it for graphical assets for my games, also for branding, and well...anything graphic design related. I often use it together with GIMP to compose the  final image, make some color adjustment, add some lighting and other effects, etc... 

### Blender: Animation, video edit, 3D workflow
Blender is a full 3D pipeline suite. It provides tools for almost every step of the production of 3D animations, from modelling, to texturing, to video editing...

I started using Blender for modelling and game design, using the (RIP) Blender Game Engine. After discovering its drawing capabilities I tried texturing, material design, and even 2D animation, which I still use now and then. I often use it to animate some characters and props I designed in Inkscape. But mostly I use it for video editing, I always used it but it was a pain to do so before I met GDQuest's Power Sequencer, which helped cut, directly and indirectly, more than 50% of my the time consumption of my previous workflow.

### LMMS: Synth sound effects, music composition, mixing
LMMS is a Digital Audio Workstation, DAW for short. It is designed to be quite similar to FruityLoops, its non-foss counterpart. It comes with a built-in VST host, a plugin that hosts VST plugins, quite like a VST interpreter, among many, many other build-in plugins, presets, demos, samples, etc... 

You can say LMMS is a Blender for audio, it provides everything, from sampling to mixing. The major problem with it is that, afak, it doesn't record, so you really need to combine LMMS and Audacity, which is not a problem imo tbh. It also provides some cool tools for automation as well which are really awesome.

### Godot: Bundle everything together, love, life
Godot Engine is an amazing set of tools to develop games, from animation to translation, provided the assets, it handles them all in game development assembling phase.

With an ever growing community, both of users and developers, and any hybrid between the two, it is a feature rich game engine.

**Add footage for all tools**

**Comment by NathanLovato** [comment]
DONE!
