### ISSUE TITLE
VisibilityNotifier2D and Enabler2D

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/gdquest-projects#7]
VisibilityNotifier is great for e.g. an infinite runner game: you can use it to `queue_free` a node that goes out of the view. I'm using that in Flossy Gnu to spawn a new object when one gets destroyed:

```gdscript
func spawn_pillar() -> void:
	var pillar := pillar_scene.instance()
	pillar.global_position = get_random_position()
	pillar.connect("tree_exited", self, "spawn_pillar")
	pillar.connect("checkpoint_reached", self, "emit_signal", ["pillar_checkpoint_reached"])
	add_child(pillar)
	position.x += spawn_interval
```

Then, show how to use VisibilityEnabler to disable e.g. an AI's behavior and things like collisions or complex nodes that are outside of the screen. I haven't used it much but it makes sense to use it for realtime AI and large levels. You can use it for optimization, to e.g. only instance parts of a world when the player moves close, and optimize large scenes.

**Comment by henriiquecampos** [comment]
Video is up, can re-open if needed
